export type StoreEntry = {
  id?: string;
  numericId?: number;
  startDate: string;
  endDate: string;
  storeName: string;
  customerName: string;
  address: string;
  customerPhone: string;
  facebookLink?: string;
  instagramLink?: string;
  googleWebsiteLink?: string;
  googleBusinessLink?: string;
  googleVerified: boolean;
  package: "PRO" | "PLUS" | string;
  hasWebsite?: boolean;
  websiteStatus?: "pending" | "processing" | "completed";
  websiteStartDate?: string;
  websiteEndDate?: string;
  websiteNote?: string;
  dateRange?: string;
  assignedTo?: string[];
  salesPerson?: string;
  paymentTypes?: "Zelle" | "Check" | "Venmo" | "Credit Card" | "Wire" | string;
  amount?: string;
  duration?: string;
  follow?: string;
  note?: string;
  serviceType?: "both" | "social" | "website";
  responsibleUserId?: string;
  seoRankInitial?: {
    rank: string;
    date: string;
  };
  seoRankLatest?: {
    rank: string;
    date: string;
    durationLabel: string;
  };
  createdAt?: number | object;
  updatedAt?: number | object;
};
